# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

# This is not ready yet.
ignored = ["github.com/katzenpost/daemons/client"]

[[override]]
  version = "v0.0.1"
  name = "github.com/katzenpost/core"

[[override]]
  version = "v0.0.1"
  name = "github.com/katzenpost/minclient"

[[constraint]]
  version = "v0.0.1"
  name = "github.com/katzenpost/authority"

[[constraint]]
  version = "v0.0.1"
  name = "github.com/katzenpost/mailproxy"

[[constraint]]
  version = "v0.0.1"
  name = "github.com/katzenpost/server"

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"
